//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_article
    {
        public int Article_Id { get; set; }
        public Nullable<System.DateTime> Article_date { get; set; }
        public int Article_UserId { get; set; }
        public string Article_Tittle { get; set; }
        public string Article_Content { get; set; }
        public Nullable<int> Article_Like_Count { get; set; }
        public Nullable<int> Article_Comment_Count { get; set; }
        public Nullable<int> Article_Views { get; set; }
    }
}
