//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_comments
    {
        public int Comment_Id { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
        public int Comment_Like_Count { get; set; }
        public int Us_Id { get; set; }
        public int Article_Id { get; set; }
        public string Comment_Content { get; set; }
        public int Comment_ParentId { get; set; }
    }
}
