//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_labels
    {
        public int Labels_Id { get; set; }
        public string Labels_Nmae { get; set; }
        public string Labels_Alias { get; set; }
        public string Labels_Description { get; set; }
    }
}
