//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_user
    {
        public int Us_Id { get; set; }
        public string Us_Ip { get; set; }
        public string Us_UserName { get; set; }
        public string Us_NickName { get; set; }
        public string Us_PassWord { get; set; }
        public string Us_Eamil { get; set; }
        public string Us_ProfilePhoto { get; set; }
        public Nullable<System.DateTime> Us_RegisterTime { get; set; }
        public Nullable<System.DateTime> Us_Birthday { get; set; }
        public Nullable<int> Us_Age { get; set; }
        public Nullable<int> Us_Sex { get; set; }
        public string Us_Phone { get; set; }
        public int Is_Del { get; set; }
    }
}
