//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bk_user_friends
    {
        public int id { get; set; }
        public int Self_id { get; set; }
        public int Friends_id { get; set; }
        public string Friends_note { get; set; }
    }
}
